# Diagnostic Services for Uber Ride Tracker

authorize:
  name: Authorize with Uber
  description: Exchange authorization code for access token after OAuth flow
  fields:
    auth_code:
      name: Authorization Code
      description: The authorization code from Uber OAuth redirect
      required: true
      example: "JG7xxxxxxxxxxxxx"
      selector:
        text:
    redirect_uri:
      name: Redirect URI
      description: The redirect URI used (must match what's in your Uber app)
      required: false
      default: "https://home.erbarraud.com/local/uber_callback.html"
      example: "https://home.erbarraud.com/local/uber_callback.html"
      selector:
        text:

test_api_access:
  name: Test API Access
  description: Test which Uber API endpoints are accessible with your credentials. Shows results in a notification.
  fields: {}

check_current_ride:
  name: Check Current Ride
  description: Manually check for an active Uber ride and display status in a notification
  fields: {}

get_ride_history:
  name: Get Ride History
  description: Fetch your recent Uber ride history and display in a notification
  fields:
    limit:
      name: Limit
      description: Number of rides to retrieve (default 5)
      required: false
      default: 5
      example: 5
      selector:
        number:
          min: 1
          max: 50
          mode: box

setup_callback:
  name: Setup OAuth Callback
  description: Manually copy the OAuth callback page to /config/www/ folder
  fields: {}