refresh_status:
  name: Refresh Status
  description: Force refresh the current ride status from Uber API
  
get_ride_history:
  name: Get Ride History
  description: Retrieve recent ride history from your Uber account
  fields:
    limit:
      name: Limit
      description: Number of rides to retrieve from history
      required: false
      default: 10
      example: 10
      selector:
        number:
          min: 1
          max: 50
          mode: box