test_api_connection:
  name: Test API Connection
  description: Test connection to Uber API and verify credentials
  fields:
    auth_code:
      name: Authorization Code
      description: OAuth authorization code from Uber (optional)
      required: false
      example: "JG7xxxxxxxxxxxxx"
      selector:
        text:

refresh_status:
  name: Refresh Status
  description: Force refresh the current ride status from Uber API
  
get_ride_history:
  name: Get Ride History
  description: Retrieve recent ride history from your Uber account
  fields:
    limit:
      name: Limit
      description: Number of rides to retrieve from history
      required: false
      default: 10
      example: 10
      selector:
        number:
          min: 1
          max: 50
          mode: box