name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    name: HACS Validation
    steps:
      - uses: actions/checkout@v3
      
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    runs-on: ubuntu-latest
    name: Hassfest Validation
    steps:
      - uses: actions/checkout@v3
      
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master